from .comfyui_nodes import NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_COMMON, NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_COMMON

from .scheduler.scheduler import NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_SCHEDULER, NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_SCHEDULER

NODE_CLASS_MAPPINGS = {**NODE_CLASS_MAPPINGS_COMMON,
                       **NODE_CLASS_MAPPINGS_SCHEDULER
                       }

NODE_DISPLAY_NAME_MAPPINGS = {**NODE_DISPLAY_NAME_MAPPINGS_COMMON,
                              **NODE_DISPLAY_NAME_MAPPINGS_SCHEDULER,
                              }

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
